name = "ergm"
uuid = "caa93091-3dc3-4b2b-9430-1aae38e8753f"
authors = ["Will Slatton <williamslatton11@gmail.com>", "Alex Kunin <Alex.Kunin@bcm.edu >"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
