name = "ergm"
uuid = "caa93091-3dc3-4b2b-9430-1aae38e8753f"
authors = ["Will Slatton <williamslatton11@gmail.com>", "Alex Kunin <Alex.Kunin@bcm.edu >"]
version = "0.1.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
